#!/usr/bin/env python3
# Flatten PDFs for Linux (GTK 4 + libadwaita).
#
# The Linux counterpart of the mac/, winforms/, and winui/ targets: for each
# PDF it is given, visible annotations are baked into ordinary page content,
# the result is validated, and only then swapped over the original in place.
# It follows GNOME conventions rather than transplanting another platform's:
# a header bar with a primary (hamburger) menu, Ctrl+O / Ctrl+Q, libadwaita
# theming that tracks the system light/dark style automatically, and a
# .desktop entry (generated by Build.sh) for launcher and open-with
# integration.
#
# Like the Windows targets, the flattening engine is PDFium (the PDF engine
# of Chrome and Edge), loaded from libpdfium.so beside this file via ctypes.
# The shared spec (app-spec.json, copied beside this file by Build.sh) is
# the single source of truth for strings, layout metrics, and version.

import ctypes
import json
import os
import queue
import sys
import tempfile
import threading

import gi

gi.require_version("Gtk", "4.0")
gi.require_version("Adw", "1")
from gi.repository import Adw, Gdk, Gio, GLib, Gtk

APP_DIR = os.path.dirname(os.path.abspath(__file__))

with open(os.path.join(APP_DIR, "app-spec.json"), encoding="utf-8") as _f:
    SPEC = json.load(_f)
STRINGS = SPEC["strings"]
LAYOUT = SPEC["layout"]
APP_ID = "local." + "".join(c for c in SPEC["name"].lower() if c.isalnum()) + ".app"

# GNOME window corner radius (libadwaita publishes no API for it); matched
# by eye, all four corners rounded equally like the other targets.
WINDOW_CORNER_RADIUS = 12

# The header bar lives inside the window (the mac target's 650x430 content
# sits below a system title bar), so the default and minimum heights grow by
# an estimate of its height, like the Windows targets do for their menus.
HEADER_BAR_ESTIMATE = 47

# Status markers in the log: check mark, en dash, ballot X, em-dash
# separator.
MARK_OK = "✓"
MARK_SKIP = "–"
MARK_FAIL = "✗"
DASH = " — "


# ---------------------------------------------------------------------------
# PDFium via ctypes.
# ---------------------------------------------------------------------------

FPDF_ANNOT_LINK = 2
FPDF_ANNOT_POPUP = 16
FLAT_NORMALDISPLAY = 0
FLATTEN_FAIL = 0
FPDF_NO_INCREMENTAL = 2
FPDF_ERR_PASSWORD = 4

WRITEBLOCK = ctypes.CFUNCTYPE(
    ctypes.c_int, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_ulong)


class FPDF_FILEWRITE(ctypes.Structure):
    _fields_ = [("version", ctypes.c_int), ("WriteBlock", WRITEBLOCK)]


_pdfium = ctypes.CDLL(os.path.join(APP_DIR, "libpdfium.so"))
_pdfium.FPDF_InitLibrary()
_pdfium.FPDF_LoadMemDocument.restype = ctypes.c_void_p
_pdfium.FPDF_LoadMemDocument.argtypes = [ctypes.c_void_p, ctypes.c_int, ctypes.c_char_p]
_pdfium.FPDF_GetLastError.restype = ctypes.c_ulong
_pdfium.FPDF_GetPageCount.argtypes = [ctypes.c_void_p]
_pdfium.FPDF_CloseDocument.argtypes = [ctypes.c_void_p]
_pdfium.FPDF_LoadPage.restype = ctypes.c_void_p
_pdfium.FPDF_LoadPage.argtypes = [ctypes.c_void_p, ctypes.c_int]
_pdfium.FPDF_ClosePage.argtypes = [ctypes.c_void_p]
_pdfium.FPDFPage_Flatten.argtypes = [ctypes.c_void_p, ctypes.c_int]
_pdfium.FPDFPage_GetAnnotCount.argtypes = [ctypes.c_void_p]
_pdfium.FPDFPage_GetAnnot.restype = ctypes.c_void_p
_pdfium.FPDFPage_GetAnnot.argtypes = [ctypes.c_void_p, ctypes.c_int]
_pdfium.FPDFAnnot_GetSubtype.argtypes = [ctypes.c_void_p]
_pdfium.FPDFPage_CloseAnnot.argtypes = [ctypes.c_void_p]
_pdfium.FPDF_SaveAsCopy.argtypes = [
    ctypes.c_void_p, ctypes.POINTER(FPDF_FILEWRITE), ctypes.c_ulong]


class FlattenError(Exception):
    """An expected, user-facing failure; the message appears in the log."""


def _fail(key, n=None):
    message = STRINGS[key]
    if n is not None:
        message = message.replace("{n}", str(n))
    raise FlattenError(message)


def is_pdf_path(path):
    return bool(path) and path.lower().endswith(".pdf")


def _count_annotations(doc, pages):
    flattenable = 0
    links = 0
    for i in range(pages):
        page = _pdfium.FPDF_LoadPage(doc, i)
        if not page:
            _fail("errorPageReadFailed", i + 1)
        try:
            for a in range(_pdfium.FPDFPage_GetAnnotCount(page)):
                annotation = _pdfium.FPDFPage_GetAnnot(page, a)
                if not annotation:
                    continue
                try:
                    subtype = _pdfium.FPDFAnnot_GetSubtype(annotation)
                    if subtype == FPDF_ANNOT_LINK:
                        links += 1
                    elif subtype != FPDF_ANNOT_POPUP:
                        flattenable += 1
                finally:
                    _pdfium.FPDFPage_CloseAnnot(annotation)
        finally:
            _pdfium.FPDF_ClosePage(page)
    return flattenable, links


def _save_document(doc):
    chunks = []

    def write_block(_self, data, size):
        try:
            chunks.append(ctypes.string_at(data, size))
            return 1
        except Exception:
            return 0

    callback = WRITEBLOCK(write_block)
    file_write = FPDF_FILEWRITE(1, callback)
    ok = _pdfium.FPDF_SaveAsCopy(doc, ctypes.byref(file_write), FPDF_NO_INCREMENTAL)
    return b"".join(chunks) if ok and chunks else None


def _validate_output(output, expected_pages):
    buffer = ctypes.create_string_buffer(output, len(output))
    doc = _pdfium.FPDF_LoadMemDocument(buffer, len(output), None)
    if not doc:
        _fail("errorValidationFailed")
    try:
        if _pdfium.FPDF_GetPageCount(doc) != expected_pages:
            _fail("errorValidationFailed")
        flattenable, links = _count_annotations(doc, expected_pages)
        if flattenable != 0:
            _fail("errorValidationFailed")
        return links
    finally:
        _pdfium.FPDF_CloseDocument(doc)


def _write_atomically(path, data):
    directory = os.path.dirname(path) or "."
    handle, temporary = tempfile.mkstemp(
        prefix="." + os.path.basename(path) + ".flatten-", dir=directory)
    try:
        with os.fdopen(handle, "wb") as f:
            f.write(data)
        os.replace(temporary, path)
    except OSError:
        try:
            os.unlink(temporary)
        except OSError:
            pass
        raise


def flatten_in_place(path):
    """Returns (page_count, flattened_count, removed_links, changed)."""
    if not is_pdf_path(path):
        _fail("errorNotPdf")
    try:
        with open(path, "rb") as f:
            data = f.read()
    except OSError:
        _fail("errorCannotOpen")

    # The buffer must outlive the document; PDFium reads it lazily.
    buffer = ctypes.create_string_buffer(data, len(data))
    doc = _pdfium.FPDF_LoadMemDocument(buffer, len(data), None)
    if not doc:
        if _pdfium.FPDF_GetLastError() == FPDF_ERR_PASSWORD:
            _fail("errorLocked")
        _fail("errorCannotOpen")
    try:
        pages = _pdfium.FPDF_GetPageCount(doc)
        if pages <= 0:
            _fail("errorNoPages")

        # A file with nothing visible to flatten is left untouched; this
        # also protects documents whose only annotations are hyperlinks.
        flattenable, links = _count_annotations(doc, pages)
        if flattenable == 0:
            return (pages, 0, 0, False)

        for i in range(pages):
            page = _pdfium.FPDF_LoadPage(doc, i)
            if not page:
                _fail("errorPageReadFailed", i + 1)
            try:
                if _pdfium.FPDFPage_Flatten(page, FLAT_NORMALDISPLAY) == FLATTEN_FAIL:
                    _fail("errorPageFlattenFailed", i + 1)
            finally:
                _pdfium.FPDF_ClosePage(page)

        output = _save_document(doc)
        if not output:
            _fail("errorSaveFailed")

        # Validate fully before touching the original: reopens, keeps the
        # page count, and retains no flattenable annotations.
        output_links = _validate_output(output, pages)
        removed = max(0, links - output_links)
    finally:
        _pdfium.FPDF_CloseDocument(doc)

    _write_atomically(path, output)
    return (pages, flattenable, removed, True)


# ---------------------------------------------------------------------------
# Work queue (mirrors shared/Core.cs's FlattenWorker).
# ---------------------------------------------------------------------------

class FlattenWorker:
    """Runs flatten batches on a background thread and reports formatted
    log lines. Callbacks are invoked on the worker thread; the UI marshals
    them with GLib.idle_add."""

    def __init__(self, log, busy):
        self._log = log
        self._busy = busy
        self._queue = queue.Queue()
        self._active = 0
        self._lock = threading.Lock()
        threading.Thread(target=self._loop, name="worker", daemon=True).start()

    @property
    def is_busy(self):
        return self._active > 0

    def enqueue(self, paths):
        pdfs = [p for p in paths if is_pdf_path(p)]
        if not pdfs:
            self._log(STRINGS["noPdfsSelected"])
            return
        with self._lock:
            self._active += 1
        self._busy(True)
        self._queue.put(pdfs)

    def _loop(self):
        while True:
            batch = self._queue.get()
            for path in batch:
                name = os.path.basename(path)
                try:
                    self._log(self._format(name, *flatten_in_place(path)))
                except Exception as error:
                    self._log(f"{MARK_FAIL} {name}{DASH}{error}")
            with self._lock:
                self._active -= 1
                done = self._active == 0
            if done:
                self._busy(False)

    @staticmethod
    def _format(name, pages, flattened, removed_links, changed):
        if not changed:
            return f"{MARK_SKIP} {name}{DASH}{STRINGS['unchangedMessage']}"
        annotations = "annotation" if flattened == 1 else "annotations"
        page_word = "page" if pages == 1 else "pages"
        line = (f"{MARK_OK} {name}{DASH}flattened {flattened} {annotations} "
                f"on {pages} {page_word}.")
        if removed_links > 0:
            links = "hyperlink" if removed_links == 1 else "hyperlinks"
            line += f" Note: {removed_links} {links} removed."
        return line


# ---------------------------------------------------------------------------
# User interface.
# ---------------------------------------------------------------------------

class MainWindow(Adw.ApplicationWindow):
    def __init__(self, app):
        super().__init__(application=app, title=SPEC["name"])
        self.set_default_size(
            LAYOUT["windowWidth"], LAYOUT["windowHeight"] + HEADER_BAR_ESTIMATE)
        self.set_size_request(
            LAYOUT["minWindowWidth"], LAYOUT["minWindowHeight"] + HEADER_BAR_ESTIMATE)

        self._quit_confirmed = False
        self.connect("close-request", self._on_close_request)

        # Spec-owned sizes land in CSS; structure and theme colors are
        # libadwaita's own (accent color, .card, .dim-label).
        css = Gtk.CssProvider()
        css.load_from_string(f"""
            .drop-title {{ font-size: {LAYOUT['titleFontSize']}px; font-weight: 600; }}
            .drop-detail {{ font-size: {LAYOUT['detailFontSize']}px; }}
            .log-view {{ font-size: {LAYOUT['logFontSize']}px; }}
            .drop-outline {{
                border: {LAYOUT['dropOutlineWidth']}px solid @accent_bg_color;
                border-radius: {WINDOW_CORNER_RADIUS}px;
            }}
        """)
        Gtk.StyleContext.add_provider_for_display(
            Gdk.Display.get_default(), css,
            Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION)

        # Header bar with the GNOME primary menu.
        header = Adw.HeaderBar()
        menu = Gio.Menu()
        menu.append("Open…", "win.open")
        menu.append("About " + SPEC["name"], "win.about")
        menu_button = Gtk.MenuButton(icon_name="open-menu-symbolic", menu_model=menu)
        header.pack_end(menu_button)

        # Content: title, detail, buttons, log. GTK margins sit outside a
        # widget's CSS box, so these provide the window padding while the
        # drop outline is drawn by a separate flush overlay below.
        content = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
        for side in ("top", "bottom", "start", "end"):
            getattr(content, f"set_margin_{side}")(LAYOUT["padding"])

        title = Gtk.Label(label=STRINGS["dropTitle"])
        title.add_css_class("drop-title")
        title.set_margin_bottom(LAYOUT["spacingAfterTitle"])
        content.append(title)

        detail = Gtk.Label(label=STRINGS["dropDetail"])
        detail.add_css_class("drop-detail")
        detail.add_css_class("dim-label")
        detail.set_wrap(True)
        detail.set_justify(Gtk.Justification.CENTER)
        detail.set_margin_bottom(LAYOUT["spacingAfterDetail"])
        content.append(detail)

        buttons = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL,
                          spacing=LAYOUT["buttonGap"], halign=Gtk.Align.CENTER)
        buttons.set_margin_bottom(LAYOUT["spacingAfterButtons"])
        self._select_button = Gtk.Button(label=STRINGS["selectPdfsButton"])
        self._select_button.connect("clicked", lambda *_: self._select_files())
        clear_button = Gtk.Button(label=STRINGS["clearLogButton"])
        clear_button.connect("clicked", lambda *_: self._log_buffer.set_text(""))
        buttons.append(self._select_button)
        buttons.append(clear_button)
        content.append(buttons)

        self._log_view = Gtk.TextView(editable=False, cursor_visible=False,
                                      monospace=True,
                                      wrap_mode=Gtk.WrapMode.WORD_CHAR)
        self._log_view.add_css_class("log-view")
        for side in ("top", "bottom", "left", "right"):
            getattr(self._log_view, f"set_{side}_margin")(8)
        self._log_buffer = self._log_view.get_buffer()
        self._log_end = self._log_buffer.create_mark(
            None, self._log_buffer.get_end_iter(), False)
        log_scroller = Gtk.ScrolledWindow(child=self._log_view, vexpand=True)
        log_scroller.add_css_class("card")
        content.append(log_scroller)

        # The drop zone is the whole content area below the header bar (the
        # header bar does not accept drops, like the other targets' menus).
        # The accent outline is a separate overlay child so it hugs the
        # window edges, ignores pointer events, and paints above the content
        # (mirrors the winui target's overlay Border).
        self._outline = Gtk.Box(visible=False, can_target=False)
        self._outline.add_css_class("drop-outline")
        overlay = Gtk.Overlay(child=content)
        overlay.add_overlay(self._outline)

        drop = Gtk.DropTarget.new(Gdk.FileList, Gdk.DragAction.COPY)
        drop.connect("enter", self._on_drag_enter)
        drop.connect("leave", self._on_drag_leave)
        drop.connect("drop", self._on_drop)
        overlay.add_controller(drop)

        toolbar = Adw.ToolbarView(content=overlay)
        toolbar.add_top_bar(header)
        self.set_content(toolbar)

        # Actions (the primary menu and accelerators bind to these).
        self._open_action = Gio.SimpleAction.new("open", None)
        self._open_action.connect("activate", lambda *_: self._select_files())
        self.add_action(self._open_action)
        about_action = Gio.SimpleAction.new("about", None)
        about_action.connect("activate", lambda *_: self._show_about())
        self.add_action(about_action)

        self.worker = FlattenWorker(
            lambda line: GLib.idle_add(self._append_log, line),
            lambda busy: GLib.idle_add(self._set_busy, busy))

    # ------- Drag and drop -------

    def _on_drag_enter(self, _target, _x, _y):
        self._outline.set_visible(True)
        return Gdk.DragAction.COPY

    def _on_drag_leave(self, _target):
        self._outline.set_visible(False)

    def _on_drop(self, _target, value, _x, _y):
        self._outline.set_visible(False)
        paths = [f.get_path() for f in value.get_files() if f.get_path()]
        self.worker.enqueue(paths)
        return True

    # ------- Actions -------

    def _select_files(self):
        pdf_filter = Gtk.FileFilter()
        pdf_filter.set_name("PDF files")
        pdf_filter.add_mime_type("application/pdf")
        pdf_filter.add_pattern("*.pdf")
        filters = Gio.ListStore.new(Gtk.FileFilter)
        filters.append(pdf_filter)
        dialog = Gtk.FileDialog(title="Select PDFs", filters=filters,
                                default_filter=pdf_filter)

        def finished(source, result):
            try:
                files = source.open_multiple_finish(result)
            except GLib.Error:
                return
            self.worker.enqueue(
                [f.get_path() for f in files if f.get_path()])

        dialog.open_multiple(self, None, finished)

    def _show_about(self):
        Adw.AboutDialog(application_name=SPEC["name"],
                        version=SPEC["version"]).present(self)

    def _on_close_request(self, _window):
        if not self.worker.is_busy or self._quit_confirmed:
            return False
        dialog = Adw.AlertDialog(heading=SPEC["name"],
                                 body=STRINGS["quitConfirmMessage"])
        dialog.add_response("cancel", "Cancel")
        dialog.add_response("quit", "Quit")
        dialog.set_response_appearance("quit", Adw.ResponseAppearance.DESTRUCTIVE)
        dialog.set_default_response("cancel")

        def responded(_dialog, response):
            if response == "quit":
                self._quit_confirmed = True
                self.close()

        dialog.connect("response", responded)
        dialog.present(self)
        return True

    # ------- Marshaled UI updates -------

    def _append_log(self, line):
        end = self._log_buffer.get_end_iter()
        if self._log_buffer.get_char_count() > 0:
            self._log_buffer.insert(end, "\n")
            end = self._log_buffer.get_end_iter()
        self._log_buffer.insert(end, line)
        self._log_view.scroll_mark_onscreen(self._log_end)
        return False

    def _set_busy(self, busy):
        self._select_button.set_sensitive(not busy)
        self._open_action.set_enabled(not busy)
        if not busy:
            display = Gdk.Display.get_default()
            if display is not None:
                display.beep()
        return False


class FlattenApp(Adw.Application):
    def __init__(self):
        super().__init__(application_id=APP_ID,
                         flags=Gio.ApplicationFlags.HANDLES_OPEN)
        self._window = None
        quit_action = Gio.SimpleAction.new("quit", None)
        quit_action.connect("activate", lambda *_: self._request_quit())
        self.add_action(quit_action)
        self.set_accels_for_action("win.open", ["<Primary>o"])
        self.set_accels_for_action("app.quit", ["<Primary>q"])

    def _ensure_window(self):
        if self._window is None:
            self._window = MainWindow(self)
        return self._window

    def _request_quit(self):
        if self._window is not None:
            self._window.close()
        else:
            self.quit()

    def do_activate(self):
        self._ensure_window().present()

    def do_open(self, files, _n_files, _hint):
        window = self._ensure_window()
        window.present()
        window.worker.enqueue([f.get_path() for f in files if f.get_path()])


if __name__ == "__main__":
    sys.exit(FlattenApp().run(sys.argv))
