// GENERATED by shared/generate.py from shared/app-spec.json - do not edit.

namespace FlattenPDFs;

internal static class Spec
{
    public const string Name = "Flatten PDFs";
    public const string Version = "1.7";

    public const string DropTitle = "Drop PDF files here";
    public const string DropDetail = "Annotations will be flattened and each PDF will be permanently updated.";
    public const string SelectPdfsButton = "Select PDFs\u2026";
    public const string ClearLogButton = "Clear Log";
    public const string NoPdfsSelected = "No PDF files were selected.";
    public const string UnchangedMessage = "no flattenable annotations; unchanged.";
    public const string ErrorNotPdf = "The item is not a PDF file.";
    public const string ErrorCannotOpen = "The PDF could not be opened.";
    public const string ErrorLocked = "The PDF is encrypted or locked. Unlock it first, then try again.";
    public const string ErrorNoPages = "The PDF contains no pages.";
    public const string ErrorCannotCreateOutput = "A temporary output PDF could not be created.";
    public const string ErrorPageReadFailed = "Page {0} could not be read.";
    public const string ErrorPageFlattenFailed = "Page {0} could not be flattened.";
    public const string ErrorSaveFailed = "A flattened PDF could not be created.";
    public const string ErrorValidationFailed = "The flattened PDF failed validation, so the original was not changed.";

    public const int WindowWidth = 650;
    public const int WindowHeight = 430;
    public const int MinWindowWidth = 520;
    public const int MinWindowHeight = 360;
    public const int Padding = 20;
    public const int Spacing = 12;
    public const int SpacingAfterButtons = 20;
    public const int ButtonGap = 8;
    public const int TitleFontSize = 24;
    public const int DetailFontSize = 13;
    public const int LogFontSize = 11;
    public const int DetailMaxWidth = 520;
    public const int LogMinHeight = 170;
    public const int DropOutlineWidth = 3;
    public const int DropOutlineCornerRadius = 10;
}
