#!/usr/bin/env python3
"""Generates per-platform constants from shared/app-spec.json.

The spec is the single source of truth for the app's user-facing strings,
layout metrics (in macOS points == 96-DPI pixels), and version. This script
emits:

  mac/Sources/Spec.swift        constants compiled into the macOS app
  windows/Sources/Spec.cs       constants compiled into the Windows app

and stamps the version into:

  mac/Resources/Info.plist      CFBundleShortVersionString / CFBundleVersion
  windows/FlattenPDFs.csproj    Version / InformationalVersion

The generated files are committed, so builds work without Python; run this
(or the macOS build script, which runs it automatically) after editing the
spec. Strings may use a {n} placeholder for a number; it becomes %d in Swift
and {0} in C#. Non-ASCII characters are emitted as escapes so file encoding
can never corrupt them.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = "GENERATED by shared/generate.py from shared/app-spec.json - do not edit."


def escape(text: str, style: str) -> str:
    out = []
    for ch in text:
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ord(ch) > 127:
            out.append(f"\\u{{{ord(ch):x}}}" if style == "swift" else f"\\u{ord(ch):04x}")
        else:
            out.append(ch)
    return "".join(out)


def swift_string(text: str) -> str:
    return '"' + escape(text.replace("{n}", "%d"), "swift") + '"'


def cs_string(text: str) -> str:
    return '"' + escape(text.replace("{n}", "{0}"), "cs") + '"'


def pascal(key: str) -> str:
    return key[0].upper() + key[1:]


def write_if_changed(path: Path, content: str) -> None:
    if not path.exists() or path.read_text(encoding="utf-8") != content:
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")


def main() -> None:
    spec = json.loads((ROOT / "shared" / "app-spec.json").read_text(encoding="utf-8"))
    strings, layout = spec["strings"], spec["layout"]

    swift = [f"// {HEADER}", "", "import CoreGraphics", "", "enum Spec {"]
    swift.append(f"    static let name = {swift_string(spec['name'])}")
    swift.append(f"    static let version = {swift_string(spec['version'])}")
    swift.append("")
    for key, value in strings.items():
        swift.append(f"    static let {key} = {swift_string(value)}")
    swift.append("")
    for key, value in layout.items():
        swift.append(f"    static let {key}: CGFloat = {value}")
    swift.append("}")
    write_if_changed(ROOT / "mac" / "Sources" / "Spec.swift", "\n".join(swift) + "\n")

    cs = [f"// {HEADER}", "", "namespace FlattenPDFs;", "", "internal static class Spec", "{"]
    cs.append(f"    public const string Name = {cs_string(spec['name'])};")
    cs.append(f"    public const string Version = {cs_string(spec['version'])};")
    cs.append("")
    for key, value in strings.items():
        cs.append(f"    public const string {pascal(key)} = {cs_string(value)};")
    cs.append("")
    for key, value in layout.items():
        cs.append(f"    public const int {pascal(key)} = {value};")
    cs.append("}")
    write_if_changed(ROOT / "windows" / "Sources" / "Spec.cs", "\n".join(cs) + "\n")

    version, build = spec["version"], spec["buildNumber"]

    plist_path = ROOT / "mac" / "Resources" / "Info.plist"
    plist = plist_path.read_text(encoding="utf-8")
    plist = re.sub(r"(<key>CFBundleShortVersionString</key>\s*<string>)[^<]*(</string>)",
                   rf"\g<1>{version}\g<2>", plist)
    plist = re.sub(r"(<key>CFBundleVersion</key>\s*<string>)[^<]*(</string>)",
                   rf"\g<1>{build}\g<2>", plist)
    write_if_changed(plist_path, plist)

    csproj_path = ROOT / "windows" / "FlattenPDFs.csproj"
    csproj = csproj_path.read_text(encoding="utf-8")
    csproj = re.sub(r"<Version>[^<]*</Version>", f"<Version>{version}.0</Version>", csproj)
    csproj = re.sub(r"<InformationalVersion>[^<]*</InformationalVersion>",
                    f"<InformationalVersion>{version}</InformationalVersion>", csproj)
    write_if_changed(csproj_path, csproj)

    print("spec generation complete")


if __name__ == "__main__":
    main()
