// GENERATED by shared/generate.py from shared/app-spec.json - do not edit.

import CoreGraphics

enum Spec {
    static let name = "Flatten PDFs"
    static let version = "1.7"

    static let dropTitle = "Drop PDF files here"
    static let dropDetail = "Annotations will be flattened and each PDF will be permanently updated."
    static let selectPdfsButton = "Select PDFs\u{2026}"
    static let clearLogButton = "Clear Log"
    static let noPdfsSelected = "No PDF files were selected."
    static let unchangedMessage = "no flattenable annotations; unchanged."
    static let errorNotPdf = "The item is not a PDF file."
    static let errorCannotOpen = "The PDF could not be opened."
    static let errorLocked = "The PDF is encrypted or locked. Unlock it first, then try again."
    static let errorNoPages = "The PDF contains no pages."
    static let errorCannotCreateOutput = "A temporary output PDF could not be created."
    static let errorPageReadFailed = "Page %d could not be read."
    static let errorPageFlattenFailed = "Page %d could not be flattened."
    static let errorSaveFailed = "A flattened PDF could not be created."
    static let errorValidationFailed = "The flattened PDF failed validation, so the original was not changed."

    static let windowWidth: CGFloat = 650
    static let windowHeight: CGFloat = 430
    static let minWindowWidth: CGFloat = 520
    static let minWindowHeight: CGFloat = 360
    static let padding: CGFloat = 20
    static let spacing: CGFloat = 12
    static let spacingAfterButtons: CGFloat = 20
    static let buttonGap: CGFloat = 8
    static let titleFontSize: CGFloat = 24
    static let detailFontSize: CGFloat = 13
    static let logFontSize: CGFloat = 11
    static let detailMaxWidth: CGFloat = 520
    static let logMinHeight: CGFloat = 170
    static let dropOutlineWidth: CGFloat = 3
    static let dropOutlineCornerRadius: CGFloat = 10
}
